/**
 * Simple working script generator for Daily Shipper
 */
module.exports = {
  generateWorkingScript(spec) {
    const title = spec.trend.title;
    const desc = spec.trend.description;
    const safeTitle = title.replace(/"/g, '\\"');
    const safeDesc = desc.replace(/"/g, '\\"');
    
    // Simple, working implementation - no template nesting issues
    return `#!/usr/bin/env node

/**
 * ${safeTitle}
 * ${safeDesc}
 * 
 * Generated by Daily Shipper - Autonomous App Builder
 */

const fs = require('fs');
const { execSync } = require('child_process');

// CLI colors
const C = {
  reset: '\\x1b[0m',
  red: '\\x1b[31m',
  green: '\\x1b[32m',
  yellow: '\\x1b[33m',
  blue: '\\x1b[34m',
  cyan: '\\x1b[36m',
  gray: '\\x1b[90m'
};

// Defined in template
const TITLE = "${safeTitle.replace(/\n/g, '\\n')}";
const DESC = "${safeDesc.replace(/\n/g, '\\n')}";

function log(msg, color) {
  console.log((C[color] || C.reset) + msg + C.reset);
}

function formatErrorLog(text) {
  return text.split('\\n').map(line => {
    if (/error|exception|failed|undefined|cannot/i.test(line)) return C.red + line + C.reset;
    if (/\\.(js|ts|py|rb|go|java)/.test(line)) return C.blue + line + C.reset;
    if (/:\\d+/.test(line)) return C.yellow + line + C.reset;
    return C.gray + line + C.reset;
  }).join('\\n');
}

function getErrorSource(src) {
  if (!src || src === 'demo') {
    return 'Error: Cannot read property undefined of undefined\\n' +
           'at Object.<anonymous> (/workspace/project/src/module.js:42:15)\\n' +
           'Error: Something went wrong in async operation';
  }
  if (src === '-') return fs.readFileSync(0, 'utf-8');
  if (fs.existsSync(src)) return fs.readFileSync(src, 'utf-8');
  return src;
}

function copyToClipboard(text) {
  try {
    const p = process.platform;
    if (p === 'darwin') execSync('echo "' + text.replace(/"/g, '\\\\"') + '" | pbcopy');
    else if (p === 'linux') execSync('printf "%s" "' + text.replace(/"/g, '\\\\"') + '" | xclip -selection clipboard');
    return true;
  } catch (e) { return false; }
}

function main() {
  const a = process.argv.slice(2);
  const src = a[0] || 'demo';
  const copy = a.includes('--copy');
  
  log('\\n📋 ' + TITLE, 'cyan');
  log('\\n' + DESC, 'gray');
  
  const err = getErrorSource(src);
  const fmt = formatErrorLog(err);
  
  console.log('\\n' + fmt);
  console.log('\\n' + C.gray + '---' + C.reset);
  log('Source: ' + src, 'blue');
  
  if (copy) {
    const ok = copyToClipboard(fmt);
    log(ok ? '✅ Copied!' : '⚠️ Copy failed', ok ? 'green' : 'yellow');
  }
  
  log('\\nDone.', 'gray');
}

main();
`;
  }
};
