/**
 * GitHub Pusher - Create repo and push to GitHub
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const https = require('https');

/**
 * Push app to GitHub as new repo
 */
async function pushToGitHub(appPath, spec) {
  const timestamp = Date.now().toString(36);
  // Use trend title for repo name
  const baseName = spec.trend.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  // Add timestamp for uniqueness
  const repoName = `${baseName}-${timestamp}`.substring(0, 50);

  console.log(`Pushing to GitHub: ${repoName}`);

  try {
    // Step 1: Initialize git repo
    console.log('Step 1: Initializing git repository...');
    execSync('git init', { cwd: appPath, stdio: 'ignore' });

    // Configure git identity for commits
    execSync('git config user.email "atlas@daily-shipper.dev"', { cwd: appPath, stdio: 'ignore' });
    execSync('git config user.name "Atlas"', { cwd: appPath, stdio: 'ignore' });

    // Step 2: Create .gitignore
    console.log('Step 2: Creating .gitignore...');
    const gitignoreContent = `node_modules
.next
.DS_Store
*.pyc
*.o
*.gem
Gemfile.lock
.bundle
target/
.env*
dist/
build/
`;
    fs.writeFileSync(path.join(appPath, '.gitignore'), gitignoreContent);

    // Step 3: Add all files
    console.log('Step 3: Adding files to git...');
    execSync('git add .', { cwd: appPath, stdio: 'ignore' });

    // Step 4: Create commit
    console.log('Step 4: Creating initial commit...');
    const commitMsg = `feat: ${spec.trend.title}

${spec.trend.description}

Generated by Daily Shipper`;
    execSync(`git commit -m "${commitMsg}"`, { cwd: appPath, stdio: 'ignore' });

    // Step 5: Create GitHub repo
    console.log('Step 5: Creating GitHub repository...');
    const createResult = await createGitHubRepo(repoName, spec.trend.description);
    
    if (!createResult.success) {
      return { success: false, error: createResult.error };
    }

    // Step 6: Push to GitHub
    console.log('Step 6: Pushing to GitHub...');
    const remoteUrl = createResult.repoUrl;
    execSync(`git remote add origin ${remoteUrl}`, { cwd: appPath, stdio: 'ignore' });
    execSync('git branch -M main', { cwd: appPath, stdio: 'ignore' });
    execSync('git push -u origin main', { cwd: appPath, stdio: 'ignore' });

    console.log(`Successfully pushed to ${remoteUrl}`);
    return { success: true, repoUrl: remoteUrl, repoName };

  } catch (error) {
    return { success: false, error: error.message };
  }
}

/**
 * Create GitHub repo via API
 */
function createGitHubRepo(repoName, description) {
  return new Promise((resolve) => {
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      resolve({ success: false, error: 'GITHUB_TOKEN not set' });
      return;
    }

    const body = JSON.stringify({
      name: repoName,
      description: description,
      private: false,
      auto_init: false
    });

    const options = {
      hostname: 'api.github.com',
      port: 443,
      path: '/user/repos',
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'User-Agent': 'Daily-Shipper/1.0.0'
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode === 201) {
          const response = JSON.parse(data);
          resolve({
            success: true,
            repoUrl: response.html_url,
            cloneUrl: response.clone_url
          });
        } else {
          resolve({
            success: false,
            error: `GitHub API returned status ${res.statusCode}: ${data.substring(0, 200)}`
          });
        }
      });
    });

    req.on('error', (error) => {
      resolve({ success: false, error: error.message });
    });

    req.write(body);
    req.end();
  });
}

/**
 * List existing repos (for cleanup)
 */
function listRepos() {
  return new Promise((resolve) => {
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      resolve({ success: false, error: 'GITHUB_TOKEN not set' });
      return;
    }

    const options = {
      hostname: 'api.github.com',
      port: 443,
      path: '/user/repos?per_page=100',
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`,
        'User-Agent': 'Daily-Shipper/1.0.0'
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode === 200) {
          const repos = JSON.parse(data);
          resolve({
            success: true,
            repos: repos.map(r => ({
              name: r.name,
              fullName: r.full_name,
              url: r.html_url,
              createdAt: r.created_at
            }))
          });
        } else {
          resolve({
            success: false,
            error: `GitHub API returned status ${res.statusCode}: ${data.substring(0, 200)}`
          });
        }
      });
    });

    req.on('error', (error) => {
      resolve({ success: false, error: error.message });
    });

    req.end();
  });
}

/**
 * Push to GitHub AND create initial PR
 */
async function pushToGitHubWithPR(appPath, prd) {
  // Derive repo name from appPath (last directory)
  const repoName = path.basename(appPath);
  
  console.log(`Creating GitHub repo: ${repoName}`);

  try {
    // Initialize git
    execSync('git init', { cwd: appPath, stdio: 'ignore' });
    execSync('git config user.email "atlas@daily-shipper.dev"', { cwd: appPath, stdio: 'ignore' });
    execSync('git config user.name "Atlas"', { cwd: appPath, stdio: 'ignore' });

    // Create .gitignore
    fs.writeFileSync(path.join(appPath, '.gitignore'), 'node_modules\n.next\n.DS_Store\n*.pyc\n*.o\n.env*\nbuild/\n');

    // Add all files
    execSync('git add .', { cwd: appPath, stdio: 'ignore' });

    // Create commit
    const commitMsg = `feat: ${prd.title}

${prd.problem.statement}

- Novelty score: ${prd.noveltyAssessment.score}/100
- Success criteria: ${prd.successCriteria.length} defined
- Tests: Tracer bullet implementation

Generated by Daily Shipper`;
    const msgFile = path.join(appPath, '.git/COMMIT_EDITMSG');
    fs.writeFileSync(msgFile, commitMsg);
    execSync('git commit -F .git/COMMIT_EDITMSG', { cwd: appPath, stdio: 'ignore' });

    // Create GitHub repo via API
    const createResult = await createGitHubRepo(repoName, prd.problem.statement);
    if (!createResult.success) {
      return { success: false, error: createResult.error };
    }

    // Push to main
    const remoteUrl = createResult.repoUrl;
    execSync(`git remote add origin ${remoteUrl}`, { cwd: appPath, stdio: 'ignore' });
    execSync('git branch -M main', { cwd: appPath, stdio: 'ignore' });
    execSync('git push -u origin main -f', { cwd: appPath, stdio: 'ignore' });

    // Create PR
    console.log('Creating PR...');
    const prResult = await createPR(repoName, prd);

    if (!prResult.success) {
      return {
        success: true,
        repoUrl: remoteUrl,
        prUrl: null,
        error: prResult.error
      };
    }

    return {
      success: true,
      repoName: repoName,
      repoUrl: remoteUrl,
      prUrl: prResult.prUrl
    };

  } catch (error) {
    return { success: false, error: error.message };
  }
}

/**
 * Create Pull Request
 */
function createPR(repoName, prd) {
  return new Promise((resolve) => {
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      resolve({ success: false, error: 'GITHUB_TOKEN not set' });
      return;
    }

    const prBody = JSON.stringify({
      title: `Initial implementation: ${prd.title}`,
      body: `# ${prd.title}

${prd.problem.statement}

## Problem

${prd.problem.painPoints.map(p => `- ${p}`).join('\\n')}

## Solution

${prd.solution.type} - ${prd.solution.inputSources.join(', ')} → ${prd.solution.outputFormats.join(', ')}

## Novelty Assessment

**Score:** ${prd.noveltyAssessment.score}/100
**Verdict:** ${prd.noveltyAssessment.verdict}

## Success Criteria

${prd.successCriteria.map(c => `- [ ] ${c.id}: ${c.name}`).join('\\n')}

## Test Plan

See \`test/index.test.js\` for unit tests and \`TEST_CHECKLIST.md\` for manual tests.

---

*Generated by [Daily Shipper](https://github.com/zenchantlive/daily-shipper)*`,
      head: 'main',
      base: 'main'
    });

    const options = {
      hostname: 'api.github.com',
      port: 443,
      path: `/repos/zenchantlive/${repoName}/pulls`,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'User-Agent': 'Daily-Shipper/1.0.0',
        'Accept': 'application/vnd.github.v3+json'
      }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode === 201) {
          const response = JSON.parse(data);
          resolve({
            success: true,
            prUrl: response.html_url,
            prNumber: response.number
          });
        } else {
          resolve({
            success: false,
            error: `PR creation failed: ${res.statusCode} - ${data.substring(0, 200)}`
          });
        }
      });
    });

    req.on('error', (error) => {
      resolve({ success: false, error: error.message });
    });

    req.write(prBody);
    req.end();
  });
}

module.exports = { pushToGitHub, pushToGitHubWithPR, createGitHubRepo, createPR, listRepos };
